name: grocerydistributorapp
description: Distributor side application for the online grocery shopping project - groceryapp.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  shared_preferences: ^0.5.10
  google_fonts: ^1.1.0
  regexed_validator: ^1.0.4
  firebase_core: ^0.5.0
  intent: ^1.4.0
  call_number: ^0.0.1
  flutter_open_whatsapp: ^0.1.2
  open_mail_app: ^0.0.3
  flutter_email_sender: ^3.0.1
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
